import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    { pattern: /^flex/ },
    { pattern: /^grid/ },
    { pattern: /^block/ },
    { pattern: /^inline/ },
    { pattern: /^hidden/ },
    { pattern: /^items-/ },
    { pattern: /^justify-/ },
    { pattern: /^gap-/ },
    { pattern: /^space-/ },
    { pattern: /^w-/ },
    { pattern: /^h-/ },
    { pattern: /^min-h-/ },
    { pattern: /^max-w-/ },
    { pattern: /^p-/ },
    { pattern: /^px-/ },
    { pattern: /^py-/ },
    { pattern: /^pt-/ },
    { pattern: /^pb-/ },
    { pattern: /^pl-/ },
    { pattern: /^pr-/ },
    { pattern: /^m-/ },
    { pattern: /^mx-/ },
    { pattern: /^my-/ },
    { pattern: /^mt-/ },
    { pattern: /^mb-/ },
    { pattern: /^text-/ },
    { pattern: /^font-/ },
    { pattern: /^bg-/ },
    { pattern: /^border/ },
    { pattern: /^rounded/ },
    { pattern: /^shadow/ },
    { pattern: /^opacity-/ },
    { pattern: /^cursor-/ },
    { pattern: /^overflow-/ },
    { pattern: /^relative/ },
    { pattern: /^absolute/ },
    { pattern: /^fixed/ },
    { pattern: /^sticky/ },
    { pattern: /^z-/ },
    { pattern: /^top-/ },
    { pattern: /^bottom-/ },
    { pattern: /^left-/ },
    { pattern: /^right-/ },
    { pattern: /^inset-/ },
    { pattern: /^transition/ },
    { pattern: /^duration-/ },
    { pattern: /^ease-/ },
    { pattern: /^scale-/ },
    { pattern: /^leading-/ },
    { pattern: /^tracking-/ },
    { pattern: /^line-clamp-/ },
    { pattern: /^truncate/ },
    { pattern: /^break-/ },
    { pattern: /^whitespace-/ },
    { pattern: /^antialiased/ },
    { pattern: /^animate-/ },
    { pattern: /^pointer-events-/ },
    { pattern: /^select-/ },
    { pattern: /^appearance-/ },
    { pattern: /^focus:/ },
    { pattern: /^hover:/ },
    { pattern: /^active:/ },
    { pattern: /^disabled:/ },
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50:  '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        giveaway: {
          DEFAULT: '#10b981',
          light:   '#d1fae5',
        },
        sale: {
          DEFAULT: '#3b82f6',
          light:   '#dbeafe',
        },
        wanted: {
          DEFAULT: '#f59e0b',
          light:   '#fef3c7',
        },
      },
      fontFamily: {
        sans: ['var(--font-assistant)', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
export default config
